# MySQL8 설정
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/miniproject?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username:  root
    password:  1111
#xml - <password>1111</password>

  # 콘솔에 SQL 출력 여부
  jpa:
    show-sql:  true
    database-platform:  org.hibernate.dialect.MySQL8Dialect

  # hibernate 설정
    database:  mysql
    hibernate:
      ddl-auto:  none
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl:  false
    properties:
      hibernate:
        format_sql:  true
        enable_lazy_load_no_trans:  true